[package]
name = "gggame"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
tokio = { version= "1", features = ["macros", "rt-multi-thread"] }
serde_json = "1"
